version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo:7.0.3
    build:
      context: .
      dockerfile: Dockerfile_mongo
    volumes:
      - vol:/data/db
      - vol_cars_photos:/app/public/cars_photos
  mongo-express:
    image: mongo-express:1.0.0-20
    ports:
      - '127.0.0.1:8081:8081'
    volumes_from:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=dev
      - ME_CONFIG_BASICAUTH_PASSWORD=dev
  node:
    build:
      context: .
      dockerfile: Dockerfile_node
    volumes_from:
      - mongo
    ports:
      - '127.0.0.1:3000:3000'
    depends_on:
      - mongo
volumes:
  vol:
  vol_cars_photos:
