name: Check scripts

on:
  push:
    branches:
      - "main"

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install-script
        run: ./install.sh
        shell: sh

  start:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Start-script
        run: ./start.sh
        shell: sh
